import React from 'react';
import { Group, Line, Text } from 'react-konva';
import { Connector } from '../types/diagram';

interface ConnectorLineProps {
  connector: Connector;
  isSelected: boolean;
  onClick: () => void;
}

export const ConnectorLine: React.FC<ConnectorLineProps> = ({
  connector,
  isSelected,
  onClick,
}) => {
  const points = connector.points.flatMap(point => [point.x, point.y]);
  const midPoint = {
    x: (connector.points[Math.floor(connector.points.length / 2)].x +
      connector.points[Math.floor(connector.points.length / 2) - 1].x) / 2,
    y: (connector.points[Math.floor(connector.points.length / 2)].y +
      connector.points[Math.floor(connector.points.length / 2) - 1].y) / 2,
  };

  return (
    <Group onClick={onClick}>
      <Line
        points={points}
        stroke={isSelected ? '#0096ff' : connector.style.stroke}
        strokeWidth={isSelected ? connector.style.strokeWidth + 1 : connector.style.strokeWidth}
        tension={0.5}
        lineCap="round"
        lineJoin="round"
      />
      {connector.text && (
        <Text
          x={midPoint.x - 50}
          y={midPoint.y - 10}
          text={connector.text}
          width={100}
          align="center"
          fontSize={12}
          fill={connector.style.stroke}
        />
      )}
    </Group>
  );

}; 
};

PREFIX ockms: <https://ontologyhub.rtx.com/RTXEnterpriseOntologies/OCKMSDigitalThreadOntology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?instance
WHERE {
    ?instance rdf:type ockms:CircuitCardAssemblyIdentifier .
}



ITEM_PN,ITEM_SN,ENG_ID,SRD,PEC,UNIT_ID,OWNING_WCC,LCN,FSC,AHE_IND,MANUF_NAME,ACCEPT_DATE,INIT_DTG,FILENAME_DTG,FILENAME_BASE

NHA_ENG_ITEM_PN,NHA_ENG_ITEM_SN,LCN,ENGINE_SN,ENG_ITEM_PN,ENG_ITEM_SN,ITEM_INST_DTG,FILENAME_DTG,FILENAME_BASE


-- HAMR.EHMLINK_ENGINE
CUST_ID,ENG_ID,ENGT_NUM_ID,ENG_SN,ON_WING_IND,SYS_CREATE_ID,SYS_CREATE_DT,SYS_DELETE_ID,SYS_DELETE_DT,ON_WATCH_IND,CONTRACT_ID
-- HAMR.ON_EQUIP_WO
AIRCRAFT_SN,JCN,FLYING_DATE,SORTIE_NUMBER,SYSTEM_CAP_STATUS,WORKORDER_STAT_DTG,WORKORDER_STATUS,WORST_DISCR_SYMBOL,DISPATCH_LOCATION,FRC,FRC_TIME_TAG_DTG,FRC_TIME_TAG_DTG_FRAC,FAULT_REPORT_DTG,REPEAT_RECUR,REPEAT_RECUR_JCN,TCTO_NUMBER,JST_NUMBER,OFP_VERSION_SW_PN,EQUIPMENT_TIME,SCH_JOB_START_DTG,SCH_JOB_COMPL_DTG,ENGINE_ITEM_PN,ENGINE_ITEM_SN,INSPECTION_TYPE,BASE_STATION_CODE,FILENAME_DTG,FILENAME_BASE
-- HAMR.COMPLETE_TASK
JCN,ENGINE_ITEM_PN,ENGINE_ITEM_SN,PKT_COMPLETED_DTG,ENGINE_OP_TIME,PKT_LEVEL_CMD_ID,VERSION_CMD_ID,BASE
-- HAMR.LCN_LIST
LCN,NOMENCLATURE,COMMON_NAME
-- HAMR.ITEM_PN_LIST
ITEM_PN,ITEM_DESC
-- HAMR.CGR_INPUT_DATA
ESN,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_POINTS,GAP_PERCENT
-- HAMR.LIFE_USE_INPUT_DATA
ESN,ENGINE_PART_NO,PREV_LIFE_USE_DTG,PREV_RUNCNT,PREV_EFI,PREV_LCF1,PREV_LCF3,PREV_TAC,PREV_AUGOT,PREV_AUGLIT,PREV_EOT,PREV_ENG_LIFE_LIMIT,PREV_FAN_LIFE_LIMIT,PREV_CORE_LIFE_LIMIT,PREV_LPT_LIFE_LIMIT,PREV_NOZ_LIFE_LIMIT,PREV_DIFF_CASE_USAGE,PREV_HPT_ROTOR_USAGE,PREV_HPC_ROTOR_USAGE,PREV_LPT_ROTOR_USAGE,PREV_BRG_RACE_USAGE,PREV_HPC_NICKEL_ROTOR_USAGE,LIFE_USE_DTG,RUNCNT,EFI,LCF1,LCF3,LCF4,TAC,AUGOT,AUGLIT,EOT
-- HAMR.LIFE_USE_OUTPUT_DATA
ESN,ENGINE_PART_NO,LIFE_USE_DTG,RUNCNT,EFT,LCF1,LCF3,LCF4,TAC,AUGOT,AUGLIT,EOT,ENG_LIFE_LIMIT,FAN_LIFE_LIMIT,CORE_LIFE_LIMIT,LPT_LIFE_LIMIT,NOZ_LIFE_LIMIT,DIFF_CASE_USAGE,HPT_ROTOR_USAGE,HPC_TITANIUM_ROTOR_USAGE,LPT_ROTOR_USAGE,BRG_RACE_USAGE,HPC_NICKEL_ROTOR_USAGE
-- HAMR.ESAS_ECL_DEFECT
ENGINE_SN,DEFECT_DTG,HOSTNAME,JCN,WCE,PART_NO,POSITION_ID,SUBPOSITION_ID,LOCATION_X,LOCATION_Y,DEFECT_NO,AREA,DELETED,VERSION,BASE,DOWNLOAD_DATE,DELETED_DATE,CREATION_DTG,DELETION_DTG
-- HAMR.ON_EQUIP_ENG_WO
AIRCRAFT_SN,JCN,FLYING_DATE,SORTIE_NUMBER,SYSTEM_CAP_STATUS,WORKORDER_STAT_DTG,WORKORDER_STATUS,WORST_DSCR_SYMBOL,DISPATCH_LOCATION,FRC,FRC_TIME_TAG_DTG,FRC_TIME_TAG_DTG_FRAC,FAULT_REPORT_DTG,REPEAT_RECUR,REPEAT_RECUR_JCN,TCTO_NUMBER,JST_NUMBER,OFP_VERSION_SW_PN,EQUIPMENT_TIME,SCH_JOB_START_DTG,SCH_JOB_COMPL_DTG,ENGINE_ITEM_PN,ENGINE_ITEM_SN,INSPECTION_TYPE,BASE_STATION_CODE,FILENAME_DTG,FILENAME_BASE
-- HAMR.ENG_ITEM_LIFE_USE
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK_NUMBER,ENGINE_PARAM_INDEX_NUMBER,LIFE_USE_DTG,ITEM_PARAM_VALUE,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- HAMR.ENG_PART_LOAD
ITEM_PN,ITEM_SN,ENG_ID,SRD,PEC,UNIT_ID,OWNING_WCC,LCN,FSC,AHE_IND,MANUF_NAME,ACCEPT_DATE,INIT_DTG,FILENAME_DTG,FILENAME_BASE
-- HAMR.ENG_SIG_HIST
ITEM_PN,ITEM_SN,LOT_NUMBER,HISTORY_DTG,HISTORY_NARRATIVE,HISTORY_NARR_BLOB,ORG_UNIT_NUMBER,ORG_UNIT_KIND,EMPLOYEE_NUMBER,HISTORY_NUMBER,BASE
-- HAMR.VIBRATION_HEALTH
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK_NUMBER,ENGINE_PARAM_INDEX_NUMBER,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,DOWNLOAD_DTG,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- HAMR.TAKEOFF_HEALTH
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK_NUMBER,ENGINE_PARAM_INDEX_NUMBER,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,DOWNLOAD_DTG,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- HAMR.CRUISE_HEALTH
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK_NUMBER,ENGINE_PARAM_INDEX_NUMBER,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,DOWNLOAD_DTG,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- HAMR.ENGINE_CONFIG
ENGINE_ITEM_PN,ENGINE_ITEM_SN,DOWNLOAD_DTG,CEDU_SW_VN,BOOT_VN,CEDU_PN,FADEC_B_PN,IOC_B_SW_VN,CLP_B_SW_VN,FADEC_A_PN,IOC_A_SW_VN,CLP_A_SW_VN,SYS_CREATE_DT
-- ECN: HAMR.CGR_INPUT_DATA
ESN,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_POINTS,GAP_PERCENT,RES1,RES2,RES3,RES4,RES5,RES6,RES7
-- HAMR.CONTROL_INPUT_DATA
ESN,LIFE_USE_DTG,OFF_VERSION,CEDU_SW_VERSION,PATH,NUM_UBL_FILES
-- HAMR.CONTROL_INPUT_DATA_FILES
ESN,LIFE_USE_DTG,FILE_NUM,UBL_FILE_ITEM
-- HAMR.F119_CYCLE_SUMMARY
AIRCRAFT_NUMBER,ESN,DTG,STREAM_NUMBER,BASE,DEPLOYMENT,MAX_T2,TAMB,MAX_T3,AVG_T3,MAX_T41,AVG_T41,MAX_N1,MAX_N2,MAX_MN,TAC,TYPE_1,TYPE_3,TYPE_4,PROCESS_DATE
-- HAMR.F119_FLEET_CYCLES
AIRCRAFT_NUMBER,ESN,DTG,STREAM_NUMBER,BASE,DEPLOYMENT,N1_LOW_GATE,N1_HIGH_GATE,N1_RANGE,CYCLE_TYPE,CYCLE_NUMBER,PROCESS_DATE
-- HAMR.F119_UBL_DEBUG
ESN,DTG,DEBUG_LOG_MISSING,UBL_EMB_VER,UBL_SUPP_VER,RUN_COUNT_NOT_INC,MISSING_DL_OR_STREAM,STREAMING_FILE_NUMBER,TACS,STREAM_FILE_MESSAGE,DATA_VALIDITY,MARKED_AS_MISSING,PASS_FIVE_PERC_CHECK,SKIPPED_STREAMING,PWLIFE_FAILED,SURCK_ERROR,FILE_LOCATION,PROCESS_DATE,NO_STREAMING_FILE
-- HAMR.LCF_INPUT_DATA
ESN,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_POINTS,GAP_PERCENT
-- ECN: HAMR.LIFE_USE_INPUT_DATA
ESN,ENGINE_PART_NO,LIFE_USE_DTG,PREV_RUNCNT,PREV_EFT,PREV_LCF1,PREV_LCF3,PREV_LCF4,PREV_TAC,PREV_AUGOT,PREV_AUGLIT,PREV_EOT,PREV_ENG_LIFE_LIMIT,PREV_FAN_LIFE_LIMIT,PREV_CORE_LIFE_LIMIT,PREV_LPT_LIFE_LIMIT,PREV_NOZ_LIFE_LIMIT,PREV_DIFF_CASE_USAGE,PREV_HPT_ROTOR_USAGE,PREV_HPC_ROTOR_USAGE,PREV_LPT_ROTOR_USAGE,PREV_BRG_RACE_USAGE,PREV_HPC_NICKEL_ROTOR_USAGE
-- ECN: HAMR.LIFE_USE_OUTPUT_DATA
ESN,ENGINE_PART_NO,LIFE_USE_DTG,RUNCNT,EFT,LCF1,LCF3,LCF4,TAC,AUGOT,AUGLIT,EOT,ENG_LIFE_LIMIT,FAN_LIFE_LIMIT,CORE_LIFE_LIMIT,LPT_LIFE_LIMIT,NOZ_LIFE_LIMIT,DIFF_CASE_USAGE,HPT_ROTOR_USAGE,HPC_TITANIUM_ROTOR_USAGE,LPT_ROTOR_USAGE,BRG_RACE_USAGE,HPC_NICKEL_ROTOR_USAGE
-- HAMR.PARTS_INPUT_DATA
ESN,PART_NO,SERIAL_NO,FILE_DTG,LCN,USAGE_IDENTIFIER,USAGE_TIME_SINCE_NEW,LIFE_LIMIT_IDENTIFIER,LIFE_LIMIT_TIME_SINCE_NEW,TIME_SINCE_LIFE_LIMIT
-- HAMR.TCY_INPUT_DATA
ESN,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_POINTS,GAP_PERCENT
-- HAMR.WEAR_INPUT_DATA
ESN,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_VALUE,GAP_FLAG,GAP_POINTS
-- TCTO: HAMR.AC_OFP_MAP
AC_OFP_VER_SW_PN,ENG_OFP_VER_SW_PN,ENG_OFP,LOT_NUMBER_SET,COMMON_NAME,USAF_DESIGNATION,TCTO
-- TCTO: HAMR.TCTO
TCTO_DATA_CODE,TCTO_NUMBER,FILENAME_BASE,SYS_CODE,PUB_DATE,RECEIVE_DATE,RESCISSION_DATE,REMOVAL_DATE,TCTO_NARR,FILENAME_DTG
-- TCTO: HAMR.SCHEDULED_TCTO
TCTO_DATA_CODE,TCTO_NUMBER,FILENAME_BASE,ITEM_PN,ITEM_SN,LOT_NUMBER,TCTO_STATUS_CODE,STATUS_DATE,JCN,WCE,FILENAME_DTG
-- TCTO: HAMR.REMIS_TMC
TYPE_MAINT_CODE,START_DATE,STOP_DATE,TYPE_MAINT_CD_DESC,ON_EQUIPMENT_IND,SUPPORT_GEN_IND,UNSCHED_MAINT_IND,R_I_COMP_IND,TCTO_IND
-- TCTO: HAMR.TCTO_STATUS_CODES
TCTO_STATUS_CODE,TCTO_DATA_ITEM
-- TCTO: HAMR.ON_EQUIP_ENG_WO
AIRCRAFT_SN,JCN,FLYING_DATE,SORTIE_NUMBER,SYSTEM_CAP_STATUS,WORKORDER_STAT_DTG,WORKORDER_STATUS,WORST_DISCR_SYMBOL,DISPATCH_LOCATION,FRC,FRC_TIME_TAG_DTG,FRC_TIME_TAG_DTG_FRAC,FAULT_REPORT_DTG,REPEAT_RECUR,REPEAT_RECUR_JCN,TCTO_NUMBER,JST_NUMBER,OFP_VERSION_SW_PN,EQUIPMENT_TIME,SCH_JOB_START_DTG,SCH_JOB_COMPL_DTG,ENGINE_ITEM_PN,ENGINE_ITEM_SN,INSPECTION_TYPE,BASE_STATION_CODE,FILENAME_DTG,FILENAME_BASE
-- TCTO: HAMR.OFF_EQUIP_ENG_WO
END_ITEM_PN,END_ITEM_SN,JCN,WORK_PACKAGE_DTG,WORKORDER_STATUS,WORKORDER_STAT_DTG,WORST_DISCR_SYMBOL,LEAD_WCE,FRC,FRC_TIME_TAG_DTG,FRC_TIME_TAG_DTG_FRAC,FAULT_REPORT_DTG,TCTO_NUMBER,JST_NUMBER,OFP_VERSION_SW_PN,SCH_JOB_START_DTG,SCH_JOB_COMPL_DTG,INSPECTION_TYPE,FILENAME_DTG,FILENAME_BASE
-- JCN: HAMR.AEFR_PROB_EVENTS
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PROBLEM_FRC,ENGINE_PROB_DTG,ENGINE_PROB_DTG_FRAC,FRC,FRC_TIME_TAG_DTG,FRC_TIME_TAG_DTG_FRAC,JCN,FILENAME_DTG,BASE,RECOVERED_SYMBOL,RELEASE
-- JCN: HAMR.AEFR_PROB_FAULTS
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PROBLEM_FRC,ENGINE_PROB_DTG,ENGINE_PROB_DTG_FRAC,ENGINE_FAULT_CODE,ENGINE_FAULT_EVD,JCN,FILENAME_DTG,BASE,RELEASE
-- JCN: HAMR.CHANGE_ACHIEVEMENT
ITEM_PN,ITEM_SN,LOT_NUMBER,CHANGE_NUMBER,FILENAME_BASE,ACHIEVED_DATE,JCN,WCE,FILENAME_DTG
-- JCN: HAMR.COMPLETE_TASK
JCN,ENGINE_ITEM_PN,ENGINE_ITEM_SN,PKT_COMPLETED_DTG,ENGINE_OP_TIME,PKT_LEVEL_CDM_ID,VERSION_CDM_ID,BASE
-- JCN: HAMR.ENGINE_WO_TASK
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PROBLEM_FRC,ENGINE_PROB_DTG,ENGINE_PROB_DTG_FRAC,AEFR_TASK_ID,JCN,TASK_ORDER,TASK_RANK,TASK_EVIDENCE,ENGINE_TASK_TIME,RELEASE,ENGINE_TASK_STATUS,BASE
-- JCN: HAMR.ON_EQUIP_MAINT_TIME
JCN,WCE,WRITEUP_SN,GENERATED_ID,WRITEUP_PN,CREATION_DTG,ACTION_START_DTG,ACTION_STOP_DTG,CREW_SIZE,CATEGORY_LABOR,MAINT_UNITS,PERF_BY_EMP_NUMBER,PERF_BY_HIST_NUM,PERF_BY_DTG,ACTION_NARR
-- JCN: HAMR.ENG_SCHED_MAINT
ITEM_PN,ITEM_SN,LOT_NUMBER,JST_NUMBER,LCN,FREQUENCY,TYPE_INTERVAL,DUE_DATE,DUE_TIME,INSPECTION_TYPE,INSPECTION_NUMBER,POSITION,CAT_NUM,DISCREPANCY_SYMBOL,SCHED_START_DTG,PRIORITY,WHEN_DISC_CODE,DEFER_CAUSE_CODE
-- JCN: HAMR.ESAS_ECL_DEFECT
ENGINE_SN,DEFECT_DTG,HOSTNAME,JCN,WCE,PART_NO,POSITION_ID,SUBPOSITION_ID,LOCATION_X,LOCATION_Y,DEFECT_NO,AREA,DELETED,VERSION,BASE,DOWNLOAD_DATE,DELETED_DATE,CREATION_DTG,DELETION_DTG
-- JCN: HAMR.OFF_EQUIP_ENG_WO
END_ITEM_PN,END_ITEM_SN,JCN,WORK_PACKAGE_DTG,WORKORDER_STATUS,WORKORDER_STAT_DTG,WORST_DISCR_SYMBOL,LEAD_WCE,FRC,FRC_TIME_TAG_DTG,FRC_TIME_TAG_DTG_FRAC,FAULT_REPORT_DTG,TCTO_NUMBER,JST_NUMBER,OFP_VERSION_SW_PN,SCH_JOB_START_DTG,SCH_JOB_COMPL_DTG,INSPECTION_TYPE,FILENAME_DTG,FILENAME_BASE
-- JCN: HAMR.OFF_EQUIP_ENG_WRITEUP
JCN,WCE,WRITEUP_SN,WRITEUP_PN,LOT_NUMBER,UNIT_ID,PERFORMING_WCC,DISCREPANCY_SYMBOL,PRIORITY,WHEN_DISC_CODE,TYPE_MAINT_CODE,ACTION_TAKEN_CODE,HOW_MAL_CODE,MAINT_REQ_NARR,MAINT_ACTION_NARR,WRITEUP_STATUS,WRITEUP_STATUS_DTG,LCN
-- JCN: HAMR.ON_EQUIP_ENG_WO
AIRCRAFT_SN,JCN,FLYING_DATE,SORTIE_NUMBER,SYSTEM_CAP_STATUS,WORKORDER_STAT_DTG,WORKORDER_STATUS,WORST_DISCR_SYMBOL,DISPATCH_LOCATION,FRC,FRC_TIME_TAG_DTG,FRC_TIME_TAG_DTG_FRAC,FAULT_REPORT_DTG,REPEAT_RECUR,REPEAT_RECUR_JCN,TCTO_NUMBER,JST_NUMBER,OFP_VERSION_SW_PN,EQUIPMENT_TIME,SCH_JOB_START_DTG,SCH_JOB_COMPL_DTG,ENGINE_ITEM_PN,ENGINE_ITEM_SN,INSPECTION_TYPE,BASE_STATION_CODE,FILENAME_DTG,FILENAME_BASE
-- JCN: HAMR.ON_EQUIP_ENG_WRITEUP
JCN,WCE,WRITEUP_SN,WRITEUP_PN,LOT_NUMBER,UNIT_ID,PERFORMING_WCC,DISCREPANCY_SYMBOL,PRIORITY,WHEN_DISC_CODE,TYPE_MAINT_CODE,ACTION_TAKEN_CODE,HOW_MAL_CODE,MAINT_REQ_NARR,MAINT_ACTION_NARR,WRITEUP_STATUS,WRITEUP_STATUS_DTG,LCN,DEFER_CAUSE_CODE,PKT_LEVEL_CDM_ID,DISC_BY_EMP_NUMBER,DISC_BY_HIST_NUM,DISCOVERED_DTG,CORR_BY_EMP_NUMBER,CORRECTED_DTG,INSP_BY_EMP_NUMBER,INSP_BY_HIST_NUM,INSPECTED_DTG,EXC_RELEASE_DTG,WSS_DATA_IND,ENGINE_ITEM_PN,ENGINE_ITEM_SN,CLASS_IND,FILENAME_DTG,FILENAME_BASE,WORK_PACKAGE_DTG,WORKORDER_STATUS,CLOSURE_DATE
-- JCN: HAMR.OFF_EQUIP_MAINT_TIME
JCN,WCE,WRITEUP_SN,GENERATED_ID,WRITEUP_PN,CREATION_DTG,ACTION_START_DTG,ACTION_STOP_DTG,CREW_SIZE,CATEGORY_LABOR,MAINT_UNITS,PERF_BY_EMP_NUMBER,PERF_BY_HIST_NUM,PERF_BY_DTG,ACTION_NARR,FILENAME_DTG,WCE_LCN,WCE_START_DTG,WCE_STOP_DTG,WCE_NARRATIVE,FILENAME_BASE
-- JCN: HAMR.SCHEDULED_TCTO
TCTO_DATA_CODE,TCTO_NUMBER,FILENAME_BASE,ITEM_PN,ITEM_SN,LOT_NUMBER,TCTO_STATUS_CODE,STATUS_DATE,JCN,WCE,FILENAME_DTG
-- IDX: HAMR.EHMLINK_HAMR_CTRL_EVENT_PARAM
ENGINE_ITEM_PN,ENGINE_ITEM_SN,EVENT_REPORT_CODE,EVENT_REPORT_DTG,EVENT_REPORT_DTG_FRAC,FAULT_REPORT_DTG,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,ENGINE_PARAM_VALUE
-- IDX: HAMR.EHMLINK_HAMR_ENGINE_TRANSIENT
ENGINE_ITEM_PN,ENGINE_ITEM_SN,EVENT_REPORT_CODE,EVENT_REPORT_DTG,EVENT_REPORT_DTG_FRAC,FAULT_REPORT_DTG,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,TRANSIENT_DTG,TRANSIENT_DTG_FRAC,ENGINE_PARAM_VALUE
-- IDX: HAMR.ENG_PARAM_TYPE
ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,ENG_PARAM_MNEMONIC,ENGINE_PARAM_NAME,ENGINE_PARAM_UNITS,CATALOG_NUMBER,DECIMAL_POSITION,IMIS_IDENTIFIER
-- IDX: HAMR.ENG_TOTAL_EXCEED
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,DOWNLOAD_RPT_DTG,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- IDX: HAMR.FUEL_FILTER_HEALTH
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,DOWNLOAD_DTG,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- IDX: HAMR.OIL_FILTER_HEALTH
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,DOWNLOAD_DTG,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- IDX: HAMR.OIL_QUANTITY_HEALTH
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,DOWNLOAD_DTG,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- IDX: HAMR.PART_ITEM_LIFE_USE
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,LIFE_USE_DTG,ITEM_PARAM_VALUE,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- IDX: HAMR.TAKEOFF_HEALTH
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,DOWNLOAD_DTG,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- IDX: HAMR.VIBRATION_HEALTH
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,DOWNLOAD_DTG,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- IDX: HAMR.ENGINE_HEALTH
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,DOWNLOAD_DTG
-- IDX: HAMR.ENG_ITEM_LIFE_USE
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,LIFE_USE_DTG,ITEM_PARAM_VALUE,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- IDX: HAMR.EHMLINK_PARM_INDEX
IDX_SEQ_NUM,DATA_BLOCK_ID,INDEX_ID,PARM_MNEMONIC,PARM_ENG_IND
-- IDX: HAMR.OIL_DEBRIS_HEALTH
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,DOWNLOAD_DTG,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- IDX: HAMR.CRUISE_HEALTH
ENGINE_ITEM_PN,ENGINE_ITEM_SN,ENGINE_PARAM_BLOCK,ENGINE_PARAM_INDEX,ENGINE_OP_TIME,ENGINE_PARAM_VALUE,DOWNLOAD_DTG,SYS_CREATE_DT,BASE,OFP_VERSION_SW_PN
-- LCN: HAMR.CGR_INPUT_DATA
ESN,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_POINTS,GAP_PERCENT,RES1,RES2,RES3,RES4,RES5,RES6,RES7
-- LCN: HAMR.CGR_OUTPUT_DATA
CGR_ID,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_VALUE,GAP_FLAG,GAP_POINTS,GAP_PERCENT,RES1,RES2,RES3,RES4,RES5,RES6
-- LCN: HAMR.ENGINE
ENGINE_ITEM_PN,ENGINE_ITEM_SN,CAMS_EQUIPMENT_ID,TMDS,ENGINE_CDM_CAGE,ENGINE_ID,SRD,PEC,UNIT_ID,OWNING_WCC,LCN,AHE_IND,MANUF_NAME,ACCEPT_DATE,INIT_DTG,QUEEN_BEE,ENG_OIL_CAPACITY,ENG_OIL_CAP_UNITS,ENG_BAL_RING1_POS,ENG_BAL_RING2_POS,ENG_ANGULAR_OFFSET,FAN_VIB_AMPL,FAN_VIB_PHASE,FAN_RPM,PRED_BAL_RING1_POS,PRED_BAL_RING2_POS,RINGS_MOVED,SYS_CREATE_DT
-- LCN: HAMR.ENG_INST_ITEM
NHA_ENG_ITEM_PN,NHA_ENG_ITEM_SN,LCN,ENGINE_SN,ENGINE_ITEM_PN,ENGINE_ITEM_SN,ITEM_INST_DTG,FILENAME_DTG,FILENAME_BASE
-- LCN: HAMR.ENG_LOCATION
AIRCRAFT_SN,LCN,ALC,FILENAME_DTG,FILENAME_BASE,ITEM_CAGE,ITEM_PN,ITEM_SN,OP_TIME_AT_INST,ITEM_INST_DTG,AIRCRAFT_OFP
-- LCN: HAMR.ENG_MAINT_STATUS
ENGINE_ITEM_PN,ENGINE_ITEM_SN,FILENAME_DTG,FILENAME_BASE,CAMS_EQUIPMENT_ID,TMSM,ENGINE_ID,SRD,PEC,UNIT_ID,OWNING_WCC,LCN,ENG_OIL_CAPACITY,ENG_OIL_CAP_UNITS,ENG_BAL_RING1_POS,ENG_BAL_RING2_POS,ENG_ANGULAR_OFFSET,FAN_RPM,FAN_VIB_AMPL,FAN_VIB_PHASE,PRED_BAL_RING1_POS,PRED_BAL_RING2_POS,RINGS_MOVED,AC_OFP_VER_SW_PN,ENG_OFP_VER_SW_PN
-- LCN: HAMR.ENG_PART_LOAD
ITEM_PN,ITEM_SN,ENG_ID,SRD,PEC,UNIT_ID,OWNING_WCC,LCN,FSC,AHE_IND,MANUF_NAME,ACCEPT_DATE,INIT_DTG,FILENAME_DTG,FILENAME_BASE
-- LCN: HAMR.ENG_SCHED_MAINT
ITEM_PN,ITEM_SN,LOT_NUMBER,JST_NUMBER,LCN,FREQUENCY,TYPE_INTERVAL,DUE_DATE,DUE_TIME,INSPECTION_TYPE,INSPECTION_NUMBER,POSITION,CAT_NUM,DISCREPANCY_SYMBOL,SCHED_START_DTG,PRIORITY,WHEN_DISC_CODE,DEFER_CAUSE_CODE,JCN,WCE,PERFORMING_WCC,WCE_LCN,WCE_START_DTG,WCE_STOP_DTG,WCE_NARRATIVE,FILENAME_DTG,FILENAME_BASE
-- LCN: HAMR.ESAS_COMPONENT_TASK
PART_DESCRIPTION,POSITION_DESCRIPTION,MAINTENANCE_LEVEL,LCN,TASK_TITLE,TASK_ID,VERSION
-- LCN: HAMR.ESAS_PART
PART_NO,ASSEMBLY_ID,PART_DESCRIPTION,LCN,SEQUENCE_NO,LRU,VERSION
-- LCN: HAMR.IMIS_XML_UBL_TCY
UBL_TCY_ID,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_VALUE,GAP_FLAG,GAP_POINTS,GAP_PERCENT,RES1,RES2,RES3,RES4,RES5,RES6,RES7,BASE,FILE_RELEASE,FILE_DATE,CREATION_DTG
-- LCN: HAMR.IMIS_XML_UBL_CGR
UBL_CGR_ID,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_VALUE,GAP_FLAG,GAP_POINTS,GAP_PERCENT,RES1,RES2,RES3,RES4,RES5,RES6,RES7,BASE,FILE_RELEASE,FILE_DATE,CREATION_DTG
-- LCN: HAMR.IMIS_XML_UBL_ITEM
UBL_ITEM_ID,PART_NO,SERIAL_NO,USAGE_IDENTIFIER,USAGE_TIME_SINCE_NEW,LIFE_LIMIT_IDENTIFIER,LIFE_LIMIT_TIME_SINCE_NEW,TIME_SINCE_LIFE_LIMIT,BASE,FILE_RELEASE,FILE_DATE
-- LCN: HAMR.IMIS_XML_UBL_LCF
UBL_LCF_ID,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_VALUE,GAP_FLAG,GAP_POINTS,GAP_PERCENT,BASE,FILE_RELEASE,FILE_DATE,CREATION_DTG
-- LCN2: HAMR.IMIS_XML_UBL_WEAR
UBL_WEAR_ID,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_VALUE,GAP_FLAG,GAP_POINTS,GAP_PERCENT,BASE,FILE_RELEASE,FILE_DATE,CREATION_DTG
-- LCN2: HAMR.LCF_INPUT_DATA
ESN,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_POINTS,GAP_PERCENT
-- LCN2: HAMR.LCF_OUTPUT_DATA
LCF_ID,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_VALUE,GAP_FLAG,GAP_POINTS,GAP_PERCENT
-- LCN2: HAMR.LCN_LIST
LCN,NOMENCLATURE,COMMON_NAME
-- LCN2: HAMR.ON_EQUIP_ENG_WRITEUP
JCN,WCE,WRITEUP_SN,WRITEUP_PN,LOT_NUMBER,UNIT_ID,PERFORMING_WCC,DISCREPANCY_SYMBOL,PRIORITY,WHEN_DISC_CODE,TYPE_MAINT_CODE,ACTION_TAKEN_CODE,HOW_MAL_CODE,MAINT_REQ_NARR,MAINT_ACTION_NARR,WRITEUP_STATUS,WRITEUP_STATUS_DTG,LCN,DEFER_CAUSE_CODE,PKT_LEVEL_CDM_ID,DISC_BY_EMP_NUMBER,DISC_BY_HIST_NUM,DISCOVERED_DTG,CORR_BY_EMP_NUMBER,CORRECTED_DTG,INSP_BY_EMP_NUMBER,INSP_BY_HIST_NUM,INSPECTED_DTG,EXC_RELEASE_DTG,WSS_DATA_IND,ENGINE_ITEM_PN,ENGINE_ITEM_SN,CLASS_IND,FILENAME_DTG,FILENAME_BASE
-- LCN2: HAMR.OFF_EQUIP_ENG_WRITEUP
JCN,WCE,WRITEUP_SN,WRITEUP_PN,LOT_NUMBER,UNIT_ID,PERFORMING_WCC,DISCREPANCY_SYMBOL,PRIORITY,WHEN_DISC_CODE,TYPE_MAINT_CODE,ACTION_TAKEN_CODE,HOW_MAL_CODE,MAINT_REQ_NARR,MAINT_ACTION_NARR,WRITEUP_STATUS,WRITEUP_STATUS_DTG,LCN,DEFER_CAUSE_CODE,PKT_LEVEL_CDM_ID,DISC_BY_EMP_NUMBER,DISC_BY_HIST_NUM,DISCOVERED_DTG,CORR_BY_EMP_NUMBER,CORRECTED_DTG,INSP_BY_EMP_NUMBER,INSP_BY_HIST_NUM,INSPECTED_DTG,EXC_RELEASE_DTG,WSS_DATA_IND,CLASS_IND,WORK_PACKAGE_DTG,WORKORDER_STATUS,CLOSURE_DATE,FILENAME_DTG,FILENAME_BASE
-- LCN2: HAMR.PARTS_INPUT_DATA
ESN,PART_NO,SERIAL_NO,FILE_DTG,LCN,USAGE_IDENTIFIER,USAGE_TIME_SINCE_NEW,LIFE_LIMIT_IDENTIFIER,LIFE_LIMIT_TIME_SINCE_NEW,TIME_SINCE_LIFE_LIMIT
-- LCN2: HAMR.PARTS_OUTPUT_DATA
PARTS_ID,PART_NO,SERIAL_NO,FILE_DTG,LCN,USAGE_IDENTIFIER,USAGE_TIME_SINCE_NEW,LIFE_LIMIT_IDENTIFIER,LIFE_LIMIT_TIME_SINCE_NEW,TIME_SINCE_LIFE_LIMIT
-- LCN2: HAMR.TCY_INPUT_DATA
ESN,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_POINTS,GAP_PERCENT
-- LCN2: HAMR.TCY_OUTPUT_DATA
TCY_ID,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_VALUE,GAP_FLAG,GAP_POINTS,GAP_PERCENT
-- LCN2: HAMR.WEAR_INPUT_DATA
ESN,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_VALUE,GAP_FLAG,GAP_POINTS,GAP_PERCENT
-- LCN2: HAMR.WEAR_OUTPUT_DATA
WEAR_ID,PART_NO,SERIAL_NO,ALGORITHM_NAME,ALGORITHM_DTG,LCN,ALGORITHM_VALUE,USAGE_REFERENCE_VALUE,LIFE_LIMIT_REFERENCE_VALUE,ENGINE_REFERENCE_VALUE,GAP_VALUE,GAP_FLAG,GAP_POINTS,GAP_PERCENT

